name: Engine Assets Tpk

on:
   push:
    branches: [ master ]
   pull_request:
    branches: [ master ]
   workflow_dispatch:
   schedule:
    - cron: '0 0 * * 0' #once per week
   
# The schedule event can be delayed during periods of high loads of GitHub Actions workflow runs
#
# ┌───────────── minute (0 - 59)
# │ ┌───────────── hour (0 - 23)
# │ │ ┌───────────── day of the month (1 - 31)
# │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
# │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
# │ │ │ │ │
# │ │ │ │ │
# │ │ │ │ │
# * * * * *
  

jobs:
    build:
     runs-on: ubuntu-latest
     steps:
     - name: Checkout Tpk Repository
       uses: actions/checkout@v4
     - name: Setup .NET
       uses: actions/setup-dotnet@v4
       with:
         dotnet-version: 6.0.x
     - name: Build
       run: dotnet build /p:Configuration=Release
       working-directory: ./Tpk.ConsoleApp/
     - name: Checkout DocumentationDumps Repository
       uses: actions/checkout@v4
       with:
        repository: 'AssetRipper/DocumentationDumps'
        path: DocumentationDumps
     - name: Make files executable
       shell: bash
       run: chmod +x ./Tpk.ConsoleApp/bin/Release/net6.0/AssetRipper.Tpk.ConsoleApp
     - name: Make tpk file
       shell: bash
       run: ./Tpk.ConsoleApp/bin/Release/net6.0/AssetRipper.Tpk.ConsoleApp --engine-assets ./DocumentationDumps/EngineAssets
     - name: Upload Uncompressed file
       uses: actions/upload-artifact@v4
       with:
         name: uncompressed_file
         path: ./uncompressed.tpk
         if-no-files-found: error
     - name: Upload Lz4 file
       uses: actions/upload-artifact@v4
       with:
         name: lz4_file
         path: ./lz4.tpk
         if-no-files-found: error
     - name: Upload Lzma file
       uses: actions/upload-artifact@v4
       with:
         name: lzma_file
         path: ./lzma.tpk
         if-no-files-found: error
     - name: Upload Brotli file
       uses: actions/upload-artifact@v4
       with:
         name: brotli_file
         path: ./brotli.tpk
         if-no-files-found: error
      